from flask import render_template
from app import app

# 1. The Home / Landing Page Route
@app.route('/')
def home():
    return render_template('index.html')

# 2. The Dashboard Route
@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

# 3. The Map Route (Crucial for your iframe!)
@app.route('/map.html')
def render_map():
    # This serves the map.html file generated by your Folium script
    return render_template('map.html')